// HUD-Elemente aus dem Sheet (Portrait/Herz/Balken-Rahmen/VS).
// Auto-generiert aus sprite.png (extract.mjs). Format: PixelSprite[]-Daten.
import type { PixelSprite } from '../art/pixelToTexture';

export const HUD_SHEET_DATA: PixelSprite[] = [
  { key: "hud_portrait_1", rows: [
    "XvXXXXXXXXXXXXXXXXwv",
    "vX..XXhKHHKKKhXX.XXv",
    "v..XXKHhhhhhhHhhX.vv",
    "v.XXHhhhhhhhhhhhX.wv",
    "v.XhhhhhhKHHhhhhhXXv",
    "v.XHhhhhKMSKHhhhHXXv",
    "v.hhhhhhHSSsSsMhKXwv",
    "v.KhhhhKSSSSSSSKhXXv",
    "v.hHKhHHSHKssMhKXXXv",
    "v.XKSSHssshssHshXXwv",
    "v.XKSoSssssssssHX.vv",
    "w.XXHsSSsSsSSSshX.Xv",
    "w..XXKSSsSMHhSSh..Xv",
    "w..XXXKoSSSSMsh...Xv",
    "v..XXhKSMSSSSKhX..Xv",
    "v.XXKjjXSSSHKjjHXXXv",
    "vvXhjjjjjKhjjjjjKXXv",
    "jvKjjhjjjjjjjjjjjhwX",
  ] },
  { key: "hud_portrait_2", rows: [
    "XXvXXXXXXXXXXXXXXXvX",
    "XvXXXXHMMMMMMhHXXXXv",
    "XvXXXHMMMMMMMMMHXhXw",
    "wvXXKMMMMMMMMMMhKhXv",
    "wvXHSMMHMHMMoMMMhhvw",
    "wvXKMSMsSssSSMMMhKXw",
    "XvXKMssssssSMMMMMKvw",
    "wv.hMSsssSSsSMMMhKXw",
    "Xv.HHsHssXsSSHHHhKXw",
    "wv.XMSSsshssSHSoMhvw",
    "Xv.XMssssssssSoSM.vv",
    "vv.XSsssSsSssSsSh.vv",
    "wv.XHsMrsMSssSHh..vw",
    "vv.XXhSSSsSSoHXX..vv",
    "vv..XXKKSsSMSKXX..vv",
    "vv.XXhKKKMSSjjjHhHvv",
    "vvXhKjjjjhhjjjjjjHvv",
    "XvXhjjjjjwjjjjjjwjvj",
  ] },
  { key: "hud_heart", rows: [
    "..hHMXXK",
    "hhHhhMMh",
    "hKvrsMSr",
    "hHrwrrrr",
    "XHrrrrrr",
    "Xhsrrrrr",
    "XXXsrrrr",
    "..hhsroh",
    "...hhM..",
  ] },
  { key: "hud_heart_empty", rows: [
    "..XHXXXK",
    "hXXXXXXX",
    "hXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "..XXXXXX",
    "...XXX..",
  ] },
  { key: "hud_bar_frame", rows: [
    "XXXXXXXXXKKKKKhKhKhKKKKKXXKKKKKKXKKKKXKKKXKKhhhhhhHhKhHhKhhKXXws",
    "XXXXhHHKKHKKKHKKKHKKKKKKKKKKKHKKKKKKKKKKHKKKHKKHHHHMHHHHHHHHHHwv",
    "Xw............................................................wv",
    "ww............................................................wv",
    "ww............................................................wv",
    "Xw............................................................wv",
    "wwvhhKwKKKKKKKKKKHKKKKHKKKKHwKKKKKKKKKKKKwwKKwKKKHHHHHKHwKHHKKXv",
    "..XXvwwwwwwwwwwwwSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwX",
  ] },
  { key: "hud_vs", rows: [
    ".HHHH..HHH.MKKKH......",
    ".MMMM.HHMMMMoooMM.....",
    ".SSSM.MMSSHSSSSSM.....",
    ".KSSMMMSSooSSMoSo.....",
    ".HHSSHHSSHooSMHHH.....",
    "..MoSMSSoHMoooSSM.....",
    "..hoooSorMMMooooS.....",
    "..MMooooMMMMMHooo.....",
    "...HroorHhooooooo.....",
    "...HKooM.MMoooorH.....",
    "....hMM....MMMM.......",
  ] },
];
