// 8 Waffen-Icons aus dem Sheet, Block-Downscale Faktor 5.
// Auto-generiert aus sprite.png (extract.mjs). Format: PixelSprite[]-Daten.
import type { PixelSprite } from '../art/pixelToTexture';

export const WEAPON_DATA: PixelSprite[] = [
  { key: "wpn_plunger", rows: [
    "............kKk",
    "...........kMYK",
    "..........KMaua",
    "..........KKuaM",
    ".........MMwaK.",
    "........MKuaM..",
    ".......MMKua...",
    ".......KKuaK...",
    "......MMuaK....",
    ".....KMaYa.....",
    ".KKKKMKua......",
    "MaKaaOaaK......",
    "MOawwaaaK......",
    "KxaaaaaaK......",
    "kKwaaaaaK......",
    ".KKaaaaaK......",
    "..KKaaaaa......",
    "....KKKKK......",
  ] },
  { key: "wpn_rubberChicken", rows: [
    "..........MMMKKK",
    ".........MMaMaKK",
    ".........MMwOOaM",
    ".........KhhwOOM",
    "........KKuOubaK",
    "........KMOuOwOK",
    "........MKYaOuY.",
    ".......MOuuOOK..",
    ".....KKMYuYYM...",
    "....OMKuuuuO....",
    "....MKuuuuKK....",
    "...KKuuwuuKK....",
    "...KYuuuuuKK....",
    "...KuuuuuuK.....",
    "..KKuuuOuYK.....",
    "KKOKuuuuuK......",
    "MaKuuuOYK.......",
    "KaOYuOYK........",
    "KMkuKMaK........",
    "MMuO............",
    "KKaa............",
  ] },
  { key: "wpn_banana", rows: [
    ".........KKKK",
    ".........KKKK",
    ".........MKOK",
    "........KMuKK",
    "........KKwYK",
    "........KuuuK",
    ".......MKuuuK",
    "......MKKuuuK",
    ".....YKKuuuKK",
    ".MMMOMKuuuuYK",
    "KMKKOMuuuuuM.",
    "KYuuuuuuuuY..",
    "KKKuuuuuKY...",
    ".KKYKKKKK....",
  ] },
  { key: "wpn_pillow", rows: [
    "..............kKh...",
    ".........hhhhhkwk...",
    ".....hKkkKwhwwwKk...",
    "kKhxKKKwwwwwwwwwh...",
    "KkwhwwwwwwwwwwwwKk..",
    "kwwwwwwwwwwwwwwwwK..",
    "hhwwwwwwwwwwwwwwwK..",
    ".KKwwwwwwwwwwwwwwKx.",
    ".hKwwwwwwwwwwwwwwwh.",
    ".hKwwwwwwwwwwwwwwwK.",
    "..KwwwwwwwwwwwwwwwK.",
    "..xKwwwwwwwwwwwwwwKh",
    "..hKwwwwwwwwwwwwwwxh",
    "...KbwwwwwwwwxwwKwwK",
    "...KxwwwwxwxxKxKhhKh",
    "...hKwwKKKKKhKk.....",
    "...KKwwKKKx.........",
    "...kKwh.............",
  ] },
  { key: "wpn_toiletBrush", rows: [
    "............kKKk.",
    "...........hkbbKh",
    "..........hhhbbbK",
    ".........KKbbbhbb",
    "........hhKbbbbbK",
    "........Kbbbbbbbk",
    "........Khbbbbbk.",
    "........bKwbbkk..",
    ".......hhwxKbk...",
    "......hwwwh......",
    ".....kkhw........",
    "....hwhwh........",
    "...kKwwK.........",
    "..hkxxK..........",
    "kkhhxh...........",
    "kkwbb............",
    "Kwbb.............",
    "kKb..............",
  ] },
  { key: "wpn_fryingPan", rows: [
    "................hkh",
    "...............KhxK",
    "..............KKxKa",
    ".............hkhxhK",
    "............hhhahK.",
    "...........kKxxhh..",
    ".....hKkKKkkxhhk...",
    "...hKKxkkkKkxK.....",
    "..KkKkkkkKxkx......",
    ".kxkkkkkkkhKKk.....",
    "Khxkkhhhhhhkxk.....",
    "KKhkhhhhhhhhxK.....",
    "KxkhhhhhhhhkxK.....",
    "xxkhhhhhhhxxk......",
    "KKkhhhhhxkxkk......",
    "khxhkKkkxxhh.......",
    ".kkhhhxxKKh........",
    "...khhKhKK.........",
  ] },
  { key: "wpn_rubberDuck", rows: [
    "......KMKKK...",
    ".....MKKuuKM..",
    "....MKuuuuuKa.",
    "....KKuuuKuuKK",
    ".MM.KKuuuMuOYK",
    "KKMKKOuuuuOOKO",
    "KKuKKKKuuuuKK.",
    "MuuuuuwuuuuOM.",
    "KuuYuwwuuuuuK.",
    "KuuuuuuuuuuYK.",
    "MKuuuuuuuuuuO.",
    ".KKuuOuuuuuY..",
    "..MKMKKOOYK...",
  ] },
  { key: "wpn_rubberBoot", rows: [
    "KMKKKKKK....",
    "KKuMMYYKk...",
    "KYMMMMYKM...",
    "KMMYYYYKM...",
    "MMYYuYYK....",
    "KKYYYYMK....",
    "KKYYYYYK....",
    "KKYYYYYKKKK.",
    "KKMYYYMMKKKK",
    "MMYYYYYYMYuK",
    "KMMYYYYYYYMK",
    "KMMMMMMMYYYK",
    "kxxxKxMMMaxx",
    "kkKKkkKKkKxk",
  ] },
];
